
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          zola build --output-dir docs
